services:
  fcp-sfd-object-processor:
    build:
      target: development
    image: fcp-sfd-object-processor-development
    container_name: fcp-sfd-object-processor-test
    command: npm run test
    env_file:
      - path: .env
        required: false
    environment:
      PORT: 3004
      NODE_ENV: development
      LOCALSTACK_ENDPOINT: http://localstack:4566
      MONGO_URI: mongodb://mongodb:27017/
    volumes:
      - ./src/:/home/node/src
      - ./test/:/home/node/test
      - ./package.json:/home/node/package.json 
      - ./coverage:/home/node/coverage
    depends_on:
    - mongodb
    - cdp-uploader


  localstack:
    env_file:
      - path: .env
        required: false