services:
  fcp-sfd-object-processor:
    ports:
      - '3004:3004'
      - '9242:9229'
    networks:
      - fcp-sfd
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  localstack:
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
  mongodb:
    ports:
      - '27017:27017'
    networks:
      - fcp-sfd
    volumes:
      - mongodb-data:/data

  cdp-uploader:
    ports:
      - '7337:7337'
    networks:
      - fcp-sfd

networks:
  fcp-sfd:
    driver: bridge
