services:
  fcp-sfd-object-processor:
    ports:
      - '3004:3004'
      - '9242:9229'
    networks:
      - fcp-sfd
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

  floci:
    ports:
      - '4566:4566'
    volumes:
      - floci-data:/app/data
    networks:
      - fcp-sfd

  floci-init:
    networks:
      - fcp-sfd
  mongodb:
    ports:
      - '27017:27017'
    networks:
      - fcp-sfd
    volumes:
      - mongodb-data:/data

  cdp-uploader:
    ports:
      - '7337:7337'
    networks:
      - fcp-sfd
  
  redis:
    networks:
      - fcp-sfd

networks:
  fcp-sfd:
    driver: bridge
    name: fcp-sfd
