name: PR Approval Bot

on:
  pull_request_review:
    types: [submitted]

jobs:
  comment-on-approval:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Post a comment on approval
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Your PR is now approved 🎉**  
            Before merging, be sure to include `#patch` or `#major` in your commit message if merging either a patch or major version.  
            This will ensure CDP deploys the correct version.  
            If merging a minor version, nothing needs to be done as these are automatically handled and deployed by CDP.  
            Full details can be found in the [CDP documentation](https://portal.cdp-int.defra.cloud/documentation/how-to/microservices.md?q=bump%20a%20either%20the%20major%20or%20patch%20version%2C%20push%20a%20commit%20with#versioning-your-microservice).  
            Thank you. 👍
