name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Depth 0 is required for branch-based versioning

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Run Tests
        run: |
          mkdir -p coverage
          chmod -R a+rw ./coverage
          docker compose -f compose.yaml -f compose.test.yaml run --build --rm 'fcp-sfd-object-processor'

      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@7fe324bec9987c5a4d0f4724b42e30c282892ceb # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
