name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Depth 0 is required for branch-based versioning

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Run Tests
        run: |
          mkdir -p coverage
          chmod -R a+rw ./coverage
          docker compose -f compose.yaml -f compose.test.yaml run --build --rm 'fcp-sfd-object-processor'

      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}