name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    if: github.run_number != 1
    name: CDP-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Full history required for SonarCloud to detect changes

      - name: Create Test Coverage Reports
        run: |
          npm ci
      - name: Run Tests
        run: |
          mkdir -p coverage
          chmod -R a+rw ./coverage
          docker compose -f compose.yaml -f compose.test.yaml run --build --rm 'fcp-sfd-object-processor'

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build and Publish
        uses: DEFRA/cdp-build-action/build@7fe324bec9987c5a4d0f4724b42e30c282892ceb # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
